#!/bin/bash


 apt-get install  \
  7zip \
  antiword \
  apache2 \
  apache2-bin \
  apache2-data \
  apache2-utils \
  arj \
  build-essential \
  bzip2 \
  bzip2-doc \
  cabextract \
  catdoc \
  clamav \
  clamav-base \
  clamav-daemon \
  clamav-freshclam \
  clamdscan \
  cpanminus \
  cpp \
  cpp-13 \
  cpp-13-x86-64-linux-gnu \
  cpp-x86-64-linux-gnu \
  dbconfig-common \
  dns-root-data \
  dovecot-core \
  dovecot-fts-xapian \
  dovecot-imapd \
  dovecot-lmtpd \
  dovecot-managesieved \
  dovecot-mysql \
  dovecot-sieve \
  exiv2 \
  fonts-glyphicons-halflings \
  gcc \
  gcc-13 \
  gcc-13-base \
  gcc-13-x86-64-linux-gnu \
  gcc-x86-64-linux-gnu \
  geoip-database \
  imagemagick \
  isa-support \
  javascript-common \
  libalien-build-perl \
  libapache2-mod-php \
  libapache2-mod-php8.3 \
  libapr1t64 \
  libaprutil1-dbd-sqlite3 \
  libaprutil1-ldap \
  libaprutil1t64 \
  libarchive-zip-perl \
  libasan8 \
  libatomic1 \
  libauthen-sasl-perl \
  libb-keywords-perl \
  libbsd-resource-perl \
  libbusiness-isbn-data-perl \
  libbusiness-isbn-perl \
  libcc1-0 \
  libcgi-fast-perl \
  libcgi-pm-perl \
  libclamav-client-perl \
  libclamav-dev \
  libclamav12 \
  libclass-data-inheritable-perl \
  libclass-inspector-perl \
  libclass-singleton-perl \
  libclass-tiny-perl \
  libclone-perl \
  libclone-pp-perl \
  libclone-choose-perl \
  libcommon-sense-perl \
  libcompress-raw-zlib-perl \
  libconfig-tiny-perl \
  libconfig-yaml-perl \
  libconvert-asn1-perl \
  libconvert-binhex-perl \
  libconvert-tnef-perl \
  libcrypt-openssl-bignum-perl \
  libcrypt-openssl-random-perl \
  libcrypt-openssl-rsa-perl \
  libcapture-tiny-perl \
  libdata-dump-perl \
  libdata-dumper-concise-perl \
  libdata-ieee754-perl \
  libdata-printer-perl \
  libdata-validate-ip-perl \
  libdatetime-locale-perl \
  libdatetime-perl \
  libdatetime-timezone-perl \
  libdbd-mysql-perl \
  libdbd-sqlite3-perl \
  libdbix-simple-perl \
  libdevel-argnames-perl \
  libdevel-caller-perl \
  libdevel-cycle-perl \
  libdevel-hide-perl \
  libdevel-lexalias-perl \
  libdevel-stacktrace-perl \
  libdevel-symdump-perl \
  libdigest-bubblebabble-perl \
  libdigest-hmac-perl \
  libemail-abstract-perl \
  libemail-address-xs-perl \
  libemail-date-format-perl \
  libemail-messageid-perl \
  libemail-mime-contenttype-perl \
  libemail-mime-encodings-perl \
  libemail-mime-perl \
  libemail-sender-perl \
  libemail-simple-perl \
  libencode-detect-perl \
  libencode-locale-perl \
  libevent-2.1-7t64 \
  libevent-pthreads-2.1-7t64 \
  libeval-closure-perl \
  libexception-class-perl \
  libexttextcat-2.0-0 \
  libexttextcat-data \
  libfcgi-bin \
  libfcgi-perl \
  libfcgi0t64 \
  libffi-checklib-perl \
  libfile-chdir-perl \
  libfile-copy-recursive-perl \
  libfile-homedir-perl \
  libfile-listing-perl \
  libfile-sharedir-install-perl \
  libfile-sharedir-perl \
  libfile-which-perl \
  libfilesys-df-perl \
  libfont-afm-perl \
  libgcc-13-dev \
  libgeo-ip-perl \
  libgeoip1t64 \
  libgssapi-perl \
  libhash-merge-perl \
  libhashkit2t64 \
  libhook-lexwrap-perl \
  libhtml-form-perl \
  libhtml-format-perl \
  libhtml-parser-perl \
  libhtml-tagset-perl \
  libhtml-template-perl \
  libhtml-tokeparser-simple-perl \
  libhtml-tree-perl \
  libhttp-cookies-perl \
  libhttp-daemon-perl \
  libhttp-date-perl \
  libhttp-message-perl \
  libhttp-negotiate-perl \
  libhwasan0 \
  libhyperscan5 \
  libidn12 \
  libimporter-perl \
  libinline-c-perl \
  libinline-files-perl \
  libinline-perl \
  libio-html-perl \
  libio-socket-inet6-perl \
  libio-socket-ssl-perl \
  libio-string-perl \
  libisl23 \
  libitm1 \
  libjemalloc2 \
  libjs-bootstrap4 \
  libjs-jquery \
  libjs-popper.js \
  libjs-requirejs \
  libjs-sizzle \
  libjson-maybexs-perl \
  libjson-perl \
  libjson-xs-perl \
  liblist-allutils-perl \
  liblist-someutils-perl \
  liblist-someutils-xs-perl \
  liblist-utilsby-perl \
  liblsan0 \
  liblua5.3-0 \
  liblua5.4-0 \
  libluajit-5.1-2 \
  libluajit-5.1-common \
  liblwp-mediatypes-perl \
  liblwp-protocol-https-perl \
  liblzf1 \
  libmail-authenticationresults-perl \
  libmail-dmarc-perl \
  libmail-dkim-perl \
  libmail-imapclient-perl \
  libmail-milter-perl \
  libmail-spf-perl \
  libmailtools-perl \
  libmath-base85-perl \
  libmath-bigint-perl \
  libmath-int128-perl \
  libmath-int64-perl \
  libmaxmind-db-common-perl \
  libmaxmind-db-reader-perl \
  libmaxmind-db-reader-xs-perl \
  libmce-perl \
  libmecab2 \
  libmemcached11t64 \
  libmime-charset-perl \
  libmime-tools-perl \
  libmime-types-perl \
  libmilter1.0.1 \
  libmodule-pluggable-perl \
  libmoox-strictconstructor-perl \
  libmoox-types-mooselike-perl \
  libmozilla-ca-perl \
  libmpc3 \
  libnamespace-autoclean-perl \
  libnet-cidr-lite-perl \
  libnet-cidr-perl \
  libnet-dns-perl \
  libnet-dns-resolver-programmable-perl \
  libnet-dns-sec-perl \
  libnet-http-perl \
  libnet-idn-encode-perl \
  libnet-libidn-perl \
  libnet-libidn2-perl \
  libnet-ldap-perl \
  libnet-netmask-perl \
  libnet-patricia-perl \
  libnet-smtp-ssl-perl \
  libnet-smtps-perl \
  libnet-ssleay-perl \
  libnetaddr-ip-perl \
  libnet-ip-perl \
  libnet-ipv6addr-perl \
  libnsl2 \
  libobject-accessor-perl \
  libole-storage-lite-perl \
  libopendbx1-mysql \
  libopendbx1-sqlite3 \
  libopendbx1t64 \
  libopendkim11 \
  libpadwalker-perl \
  libparams-validationcompiler-perl \
  libparse-recdescent-perl \
  libpath-class-perl \
  libpegex-perl \
  libperl4-corelibs-perl \
  libperl-critic-perl \
  libpod-coverage-perl \
  libpod-parser-perl \
  libpod-simple-perl \
  libpod-spell-perl \
  libppix-quotelike-perl \
  libppix-regexp-perl \
  libppix-utilities-perl \
  libppix-utils-perl \
  libppi-perl \
  libprotobuf-lite32t64 \
  libquadmath0 \
  librbl1 \
  libregexp-common-perl \
  libsereal-decoder-perl \
  libsereal-encoder-perl \
  libsendmail-pmilter-perl \
  libscope-guard-perl \
  libsocket-perl \
  libsocket6-perl \
  libsombok3 \
  libspecio-perl \
  libsql-abstract-perl \
  libssl-dev \
  libstring-format-perl \
  libsub-info-perl \
  libsub-uplevel-perl \
  libsys-hostname-long-perl \
  libsys-sigaction-perl \
  libtask-weaken-perl \
  libterm-size-any-perl \
  libterm-size-perl-perl \
  libterm-table-perl \
  libtest-deep-perl \
  libtest-exception-perl \
  libtest-failwarnings-perl \
  libtest-fatal-perl \
  libtest-file-perl \
  libtest-file-sharedir-perl \
  libtest-harness-perl \
  libtest-leaktrace-perl \
  libtest-manifest-perl \
  libtest-nowarnings-perl \
  libtest-object-perl \
  libtest-output-perl \
  libtest-perl-critic-perl \
  libtest-pod-coverage-perl \
  libtest-pod-perl \
  libtest-regexp-perl \
  libtest-requires-perl \
  libtest-simple-perl \
  libtest-subcalls-perl \
  libtest-warnings-perl \
  libtest2-suite-perl \
  libtext-aligner-perl \
  libtext-balanced-perl \
  libtext-diff-perl \
  libtext-table-perl \
  libtext-unidecode-perl \
  libthrowable-perl \
  libtie-ixhash-perl \
  libtimedate-perl \
  libtsan2 \
  libunicode-linebreak-perl \
  libunbound8 \
  libubsan1 \
  liburi-perl \
  libvbr2 \
  libversion-perl \
  libwww-perl \
  libwww-robotrules-perl \
  libxapian30 \
  libxml-libxml-perl \
  libxml-namespacesupport-perl \
  libxml-parser-perl \
  libxml-sax-base-perl \
  libxml-sax-expat-perl \
  libxml-sax-perl \
  libxstring-perl \
  libxxx-perl \
  libyaml-libyaml-perl \
  libyaml-perl \
  libyaml-pp-perl \
  mailcap \
  mecab-ipadic \
  mecab-ipadic-utf8 \
  mecab-utils \
  node-jquery \
  opendkim \
  opendkim-tools \
  p7zip-full \
  perl-doc \
  perltidy \
  php-apcu \
  php-cli \
  php-common \
  php-curl \
  php-gd \
  php-intl \
  php-json \
  php-mbstring \
  php-mysql \
  php-pear \
  php-xml \
  php8.3-cli \
  php8.3-common \
  php8.3-curl \
  php8.3-gd \
  php8.3-intl \
  php8.3-mbstring \
  php8.3-mysql \
  php8.3-opcache \
  php8.3-phpdbg \
  php8.3-readline \
  php8.3-xml \
  poppler-utils \
  postfix \
  postfix-mysql \
  pyzor \
  razor \
  re2c \
  redis-server \
  redis-tools \
  rspamd \
  ssl-cert \
  sse3-support \
  tar \
  tesseract-ocr \
  tesseract-ocr-eng \
  tnef \
  unrar \
  unzip \
  zip \
  zlib1g-dev
